"""Initial migration including user_id

Revision ID: 2a2ae38b1474
Revises: 
Create Date: 2025-07-06 12:24:55.072916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2ae38b1474'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('original_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('short_url',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.create_foreign_key('fk_url_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('short_url',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('original_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
